#!/usr/bin/env python3
"""
Zero Touch Provisioning (ZTP) Script
-----------------------------------
Automatically detects new config files generated by GUI,
waits for devices to be reachable, and pushes configuration
over SSH using Netmiko. Runs continuously under systemd.
"""

import os
import time
import threading
import glob
from loguru import logger
from netmiko import ConnectHandler

# === Configuration ===
BASE_DIR = "/home/student/advanced-netman"
CONFIG_FOLDER = f"{BASE_DIR}/generated-configs"
LOG_FILE = f"{BASE_DIR}/logs/ztp.log"  # optional logs folder

USERNAME = "admin"
PASSWORD = "admin"
DEVICE_TYPE = "arista_eos"
PING_INTERVAL = 3  # seconds

# === Logger Setup ===
os.makedirs(os.path.dirname(LOG_FILE), exist_ok=True)
logger.add(LOG_FILE, rotation="10 MB", level="INFO", format="{time} | {level} | {message}")

# === Discover Configs ===
def discover_devices(config_folder):
    """Discover all config files inside generated-configs and map to devices."""
    device_map = {}
    for cfg_file in glob.glob(f"{config_folder}/*.cfg"):
        device_name = os.path.basename(cfg_file).split(".")[0]
        device_map[device_name] = {
            "device_type": DEVICE_TYPE,
            "username": USERNAME,
            "password": PASSWORD,
            "host": None,  # to be filled dynamically when reachable
            "config_file": cfg_file
        }
    return device_map


# === Utility: Ping Function ===
def is_reachable(ip):
    """Return True if IP responds to ping."""
    return os.system(f"ping -c 1 -W 2 {ip} > /dev/null 2>&1") == 0


# === Configuration Push Function ===
def push_config(device_name, ip, cfg_file):
    """SSH into device and push config."""
    try:
        logger.info(f"[{device_name}] Connecting to {ip} ...")
        conn = ConnectHandler(
            device_type=DEVICE_TYPE,
            host=ip,
            username=USERNAME,
            password=PASSWORD
        )
        conn.enable()
        with open(cfg_file) as f:
            config_lines = f.read().splitlines()
        conn.send_config_set(config_lines)
        conn.save_config()
        conn.disconnect()
        logger.success(f"[{device_name}] Configuration pushed successfully to {ip}")
    except Exception as e:
        logger.error(f"[{device_name}] Failed to push config: {e}")


# === Main Worker Function ===
def ztp_worker(device_name, cfg_file, possible_ips):
    """Ping until one IP is reachable, then push config."""
    logger.info(f"[{device_name}] Watching for device to appear...")
    while True:
        for ip in possible_ips:
            if is_reachable(ip):
                logger.info(f"[{device_name}] Device is reachable at {ip}.")
                push_config(device_name, ip, cfg_file)
                return
        logger.info(f"[{device_name}] Not reachable yet. Retrying in {PING_INTERVAL}s...")
        time.sleep(PING_INTERVAL)


# === Main Function ===
def main():
    logger.info("========== ZTP SERVICE STARTED ==========")
    devices = discover_devices(CONFIG_FOLDER)
    if not devices:
        logger.warning("No configuration files found in generated-configs folder.")
    else:
        logger.info(f"Discovered {len(devices)} devices to configure: {list(devices.keys())}")

    # Define your DHCP pool range for scanning (e.g., management network 10.100.0.0/24)
    mgmt_network_prefix = "10.100.0."
    possible_ips = [f"{mgmt_network_prefix}{i}" for i in range(10, 51)]  # adjust range to your pool

    threads = []
    for device_name, device_info in devices.items():
        thread = threading.Thread(target=ztp_worker, args=(device_name, device_info["config_file"], possible_ips))
        thread.start()
        threads.append(thread)

    # Wait for all threads to finish
    for t in threads:
        t.join()

    logger.success("========== ZTP CONFIGURATION COMPLETE ==========")


if __name__ == "__main__":
    main()
